kind: Service
apiVersion: v1
metadata:
  name: redis-broker
spec:
  clusterIP: None
  selector:
    app: redis-broker
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-broker
data:
  redis.conf: |-
    maxmemory-policy volatile-lru
    appendonly yes
    aof-use-rdb-preamble yes
    auto-aof-rewrite-percentage 50
    auto-aof-rewrite-min-size 64mb
    client-output-buffer-limit pubsub 64mb 32mb 60
    lazyfree-lazy-eviction yes
    lazyfree-lazy-expire yes
    lazyfree-lazy-server-del yes
    slave-lazy-flush yes
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: redis-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-broker
  serviceName: redis-broker
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ssd
      resources:
        requests:
          storage: 32Gi
  template:
    metadata:
      labels:
        app: redis-broker
    spec:
      volumes:
      - name: config
        configMap:
          name: redis-broker
      containers:
      - name: redis
        image: redis:4.0.10-alpine
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf", "--loglevel", "verbose", "--maxmemory", "1g"]
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /etc/redis
        resources:
          requests:
            cpu: 250m
            memory: 2G
          limits:
            cpu: 1000m
            memory: 2G
